Update branch.yaml

diff --git a/.github/workflows/branch.yaml b/.github/workflows/branch.yaml
--- a/.github/workflows/branch.yaml
+++ b/.github/workflows/branch.yaml
@@ -15,12 +15,11 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     steps:
-    
+
       - name: Block main branch
         run: |
           if [ "${{ github.event.inputs.branch }}" == "main" ]; then
             echo "ERROR: Cannot deploy main branch from this workflow."
-            echo "Use pipeline.yml for main branch deployments."
             exit 1
           fi
 
@@ -30,13 +29,13 @@ jobs:
 
       - name: Login to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
       - name: Inject API key
         run: |
-          echo "Files in current directory:"
           ls -la
           sed -i 's/TMDB_API_KEY_PLACEHOLDER/${{ secrets.TMDB_API_KEY }}/g' index.html
-          echo "Injection done"
-          
+          grep -c 'TMDB_API_KEY_PLACEHOLDER' index.html && echo "FAILED - placeholder still exists" || echo "SUCCESS - placeholder replaced"
+
       - name: Build and push
         run: |
           docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/movies:${{ github.event.inputs.branch }} .
